/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iu;

import Controladores.ControladorMonitoreoJuegos;
import Vistas.VistaMonitoreoJuegos;
import java.util.ArrayList;
import logica.Administrador;
import logica.Juego;
import logica.Participante;

/**
 *
 * @author Fernando
 */
public class MonitoreoJuegos extends javax.swing.JDialog implements VistaMonitoreoJuegos {

    /**
     * Creates new form MonitoreoJuegos
     */
    
    private ControladorMonitoreoJuegos controlador;
    public MonitoreoJuegos(java.awt.Frame parent, boolean modal, Administrador administrador) {
        super(parent, modal);
        initComponents();
        controlador = new ControladorMonitoreoJuegos(this, administrador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jJuegos = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jJugadores = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jJuegos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jJuegosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jJuegos);

        jJugadores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jJugadoresValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jJugadores);

        jLabel1.setText("Juegos en rogreso:");

        jLabel2.setText("Jugadores:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jJuegosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jJuegosValueChanged
        seleccionJuego();
    }//GEN-LAST:event_jJuegosValueChanged

    private void jJugadoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jJugadoresValueChanged
        
    }//GEN-LAST:event_jJugadoresValueChanged

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jJuegos;
    private javax.swing.JList jJugadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarJuegos(ArrayList<Juego> juegosEnProgreso) {
        jJuegos.setListData(juegosEnProgreso.toArray());
    }
    
    private void seleccionJuego() {
        Juego juego = (Juego)jJuegos.getSelectedValue();
        controlador.seleccionJuego(juego);
    }

    @Override
    public void mostrarJugadores(ArrayList<Participante> participantes) {
        jJugadores.setListData(participantes.toArray());
    }
}
